### ISSUE TITLE
Add option to rename asset

### ISSUE THREAD

**Issue by brabeji** [timkelty/shipit-assets#9]
Be it folder or file. I know this could be out of scope, so please advise.

**Comment by timkelty** [comment]
Can you just quickly outline your use-case?

**Comment by travco** [comment]
Hey @brabeji, is there any chance you can clue us into your use case? It's possible (because there's still pretty terrible documentation on this taskset) you (reasonably) missed an already existing feature in the config.

Or, since it's been a while, if you managed to solve the problem could you share your solution and close the issue? Might be helpful for others, or us while we build documentation.

**Comment by brabeji** [comment]
Hi, guys

Sorry that I totally missed this. I needed to rename my local config file from something like `config.propduction.json` to `config.json` on deploy. It the end, reading config values from env vars in my node.js app was the solution.

Thanks for your patience

**Comment by travco** [comment]
@brabeji No problem,

Would you mind closing the issue since it's resolved on your end?
